version: '3'
# Define services
services:
  # App Services
  api:
    # Configuration for building the docker image for the service
    build:
      # Use an image built from the specified dockerfile in the current directory.
      context: .
      dockerfile: Dockerfile
    container_name: todo_test_api
    environment:
      - MONGO_URL=mongodb://mongo:27017
      - MONGO_TODO_DB=TodoDb
      - MONGO_MAX_POOL_SIZE=10
      - MONGO_CONNECTION_TIMEOUT=20
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
      - JAEGER_SAMPLER_PARAM=1
      - JAEGER_SAMPLER_TYPE=probabilistic
      - JAEGER_SERVICE_NAME=go-todo-app
    ports:
      - "8080:8080" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    restart: unless-stopped
    depends_on:
      - mongo
  mongo:
    image: mongo:3
    container_name: todo_test_db
    ports:
      - '27017:27017'



