version: '3'
services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
      target: ${FRONTEND_BUILD_TARGET:-dev} # use "prod" for production
    ports:
      - "5000:80"
    environment:
      BASE_API_URL: ${BACKEND_URL:-http://localhost:8080}
    depends_on:
      - api
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${BACKEND_BUILD_TARGET:-dev} # use "prod" for production
    environment:
      - MONGO_URL=mongodb://mongo:27017
      - MONGO_TODO_DB=TodoDb
      - MONGO_MAX_POOL_SIZE=10
      - MONGO_CONNECTION_TIMEOUT=20
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
      - JAEGER_SAMPLER_PARAM=1
      - JAEGER_SAMPLER_TYPE=probabilistic
      - JAEGER_SERVICE_NAME=go-todo-app
      - GIN_MODE=debug
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - mongo
      - jaeger
  mongo:
    image: mongo:3
    ports:
      - '27017:27017'
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "5775:5775/udp"
      - "16686:16686"
